/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119785-g8ea2b993fd-20250601"
#endif /* AVUTIL_FFVERSION_H */
